# Notebook 0 : Introduction to Python


Some things to remember about python: 

    1. when you use the .range() in for loops. It is not inclusive so it goes from 0 ... specified range value
    2. take in input with the 'input' key 
    3. 

In [2]:
# Anonyomous functions and basics 
plusOne = lambda x: x + 1
def plus_one(x):
    updatedList = map(plusOne, x)
    return updatedList
    
    
numbers = [1,2,3,4,5]
zz = list(plus_one(numbers))
print(zz)

[2, 3, 4, 5, 6]


In [3]:
# List comprehension example

word = "word"
characters = [char for char in word]
print(characters)


# Conditional list comprehension

number_list = [ x for x in range(20) if x % 2 == 0]
print(number_list)


['w', 'o', 'r', 'd']
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


# Introduction to Numpy and Pandas Library 

__NumPy__ is an open source Python package for scientific computing. NumPy supports large, multidimensional arraysa dn matrices. It also supports a collection of mathematical functions not found in Python's standard math library. 

__Pandas__ is an open source data analysis library for Python used for stroing, cleaning, wrangling, and analyzing data. 

First, lets import he tnumpy and Pands libary. Its custom in data sciecne to import Pandas and Numpy with the alias.

In [4]:
import pandas as pd
import numpy as np

## The Numpy ndarray

The main workhorse of Numpy is it's multidimensional array class called ndarray. This allows us to build and work with one dimensional, two dimensional, or even N-dimensional array of numbers.

We can build a one dimensional ndarray but passing a python list to the ```np.array()``` function.

In [5]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [6]:
# Checking the types of objects
type(x)

numpy.ndarray

 The nice thing about using Numpy arrays to store numerical values is that we can perform mathematical operations on them. For instance, if we want to omulitply every value in x by 5 and sotre the result in a new array y , then we can do the following

In [7]:
y = 5*x   # this is essentially matrix multiplication  ->  [5] * [1,2,3,4,5]
print(y)

[ 5 10 15 20 25]


If we want to add two ndarray's of equal length together we can do that too 

In [8]:
z = x + y 
print(z)

[ 6 12 18 24 30]


If we want to create two dimensional arrays we simply pass a list of lists to the np.array() function. The list in the first of lists in the list becomes the rows

In [9]:
twoDimArr = np.array([[1,2,3,4,5], [6,7,8,9,10]], dtype = int)
print(twoDimArr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


We can access elements of Numpy arrays in a ways similar to thewway we acess python lists

In [10]:
oneDimArray = [1,2,3,4,5]
print(oneDimArray[0:4])    # [inclusive, exclusive]
print(oneDimArray[:2])     # print to up to index two
print(oneDimArray[2:0])    # print from index 2 to the end

[1, 2, 3, 4]
[1, 2]
[]


## Slicing and multi-dimensional array

In [11]:
xx = np.array([1,2,3,4,5], dtype=int)
yy = 5*xx
zz = xx + yy

multiDim = np.array([xx,yy,zz])
print(multiDim)

[[ 1  2  3  4  5]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]]


We can slice up the two dimensional array by doing slices along ros and columns. Let's suppose we wanted to carve out the scond row of ```multiDim```

In [12]:
# Slicing the rows from a multi dimensional array

print(multiDim[0,:])   # standalone colon means just give me everything since you didn't specify a range
print(multiDim[1,:])
print(multiDim[2,:])
print("--------")

# Slicing up a multi dimensional array for its columns

print(multiDim[:,0])
print(multiDim[:,1])
print("--------")

# Give me the first two rows and the first two elements of each column

print(multiDim[0:2, 0:2])
print("--------")

# Give me just the first element

print(multiDim[0,0])

[1 2 3 4 5]
[ 5 10 15 20 25]
[ 6 12 18 24 30]
--------
[1 5 6]
[ 2 10 12]
--------
[[ 1  2]
 [ 5 10]]
--------
1


## Mathematical Operations on multi-dimensional arrays

In [13]:
# Summing up a matrix

summy = np.sum(multiDim)
matrixSum = multiDim.sum()
print(matrixSum)
print(summy)

180
180


### Summing up by rows or columns

If instead we just wanted to sumal ong the rows or columns, we can throw in the axis parameter

    - axis=0 , sum across the rows of the given matrix
    - axis=1 , sum across the columns of the given matrix

In [14]:
print("MATRIX")
print(multiDim)
print("--------")
print("summing across the columns")
print(np.sum(multiDim, axis=0))

MATRIX
[[ 1  2  3  4  5]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]]
--------
summing across the columns
[12 24 36 48 60]


In [15]:
print("MATRIX")
print(multiDim)
print("--------")
print("summing across the rows")
print(np.sum(multiDim, axis=1))

MATRIX
[[ 1  2  3  4  5]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]]
--------
summing across the rows
[15 75 90]


### Conditional Operation

We can also index into an array by conditions

In [16]:
# grabbing the first row of mulitDim
firstRow = multiDim[0,:]
print(firstRow)

valuesLessThanThree = firstRow < 3  # returns a boolean array
extractedValues = firstRow[valuesLessThanThree] # extracting based off that boolean array
print(extractedValues)

[1 2 3 4 5]
[1 2]


### More Numpy Mathematical Functions

Numpy includes all the functions and mathematical constants in Pyhton's standard math libray, like logarithms, exponentiation, and even pi

In [17]:
print(np.log(np.exp(1)))
print(np.log2(16))
print(np.log10(1000))
print(np.pi)

1.0
4.0
3.0
3.141592653589793


In [18]:
# applying mathematical functions to array

u = [10, 100, 1000, 10000]
np.log10(u)

array([1., 2., 3., 4.])

## Pandas Library 
First we'll create a Series with a list of integer values

In [19]:
my_series = pd.Series([17,3,7,9,8,10])

We can print the Series object by executing the series name in a Python cell


In [20]:
print(my_series)

0    17
1     3
2     7
3     9
4     8
5    10
dtype: int64


In [21]:
# creating an array for the series 
values = my_series.values
print(values)    # the type of this returned array is actually a numpyArray! 

[17  3  7  9  8 10]


In [22]:
# fetching just the available indices
print(my_series.index)

RangeIndex(start=0, stop=6, step=1)


What we can do here is essentially manipulat this concept and create a hashable array. Example below

In [23]:
top_tech2016 = pd.Series([215.6, 173.9, 135.9, 135.1, 90.2], 
                         index=["Apple", "Samsung", "Amazon", "Foxconn", "Alphabet"])

In [24]:
print(top_tech2016)

Apple       215.6
Samsung     173.9
Amazon      135.9
Foxconn     135.1
Alphabet     90.2
dtype: float64


In [25]:
top_tech2016.index.values  # this is how you query out the index names
top_tech2016.values # querying just the values

array([215.6, 173.9, 135.9, 135.1,  90.2])

In [26]:
# Example: Query me all the items who associated values are over 100 

extractedValues = top_tech2016[ top_tech2016 > 100]
print(extractedValues)
print("----------------")

# getting the names of just the companies

extractedNames = top_tech2016.index.values
print(extractedNames)

Apple      215.6
Samsung    173.9
Amazon     135.9
Foxconn    135.1
dtype: float64
----------------
['Apple' 'Samsung' 'Amazon' 'Foxconn' 'Alphabet']


In [27]:
# Querying to see if elements are in the series

print("Amazon" in top_tech2016)
print("AT&T" in top_tech2016)

True
False


### The Pandas DataFrame

The key data structure in Pandas is the __DataFrame__ object. A DataFrame is basically a tabular data strucutre, with rows and columns. Rows have a specific index to acess them, which can be any name or value. The columns are just Pandas Series. The Pandas DataFrame data structure can be seen as a spreadsheet, but i is much more flexible. 

First, let's create a DataFrame from scratch by in a Python dictionary.

In [28]:
data = {'year': [2010, 2011, 2012, 2010, 2011, 2012, 2010, 2011, 2012],
        'team': ['FCBarcelona', 'FCBarcelona', 'FCBarcelona', 'RMadrid', 'RMadrid', 'RMadrid', 'ValenciaCF',
                 'ValenciaCF', 'ValenciaCF'],
        'wins':   [30, 28, 32, 29, 32, 26, 21, 17, 19],
        'draws':  [6, 7, 4, 5, 4, 7, 8, 10, 8],
        'losses': [2, 3, 2, 4, 2, 5, 9, 11, 11]
        }

We'll conver this data to a Pandas DataFrame as follows:

In [29]:
football = pd.DataFrame(data)
print(football)

   year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2
5  2012      RMadrid    26      7       5
6  2010   ValenciaCF    21      8       9
7  2011   ValenciaCF    17     10      11
8  2012   ValenciaCF    19      8      11


Note that each list in dictionary has become a column in our DataFrame with the associated dictionary key as the column name.

Now, the order that the columns are are situated is a little wierd (not that it did it alphabetically). If instead we want the columns in the order year, team, wins, draws, losses we can pass this oredering of the columns when we create the DataFrame. 

In [30]:
football = pd.DataFrame(data, columns=['year','team', 'wins', 'draws', 'losses']) # have to be the same as dict
print(football)

   year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2
5  2012      RMadrid    26      7       5
6  2010   ValenciaCF    21      8       9
7  2011   ValenciaCF    17     10      11
8  2012   ValenciaCF    19      8      11


We displayed the DataFrame using the print() function, but Pandas has their own pre-baked display functions

In [31]:
# displaying the first 5 rows, .head()
football.head()

year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2

In [32]:
# displaying more rows than just 5
football.head(10)

year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2
5  2012      RMadrid    26      7       5
6  2010   ValenciaCF    21      8       9
7  2011   ValenciaCF    17     10      11
8  2012   ValenciaCF    19      8      11

In [33]:
# displaying the last 5 rows
football.tail()

year        team  wins  draws  losses
4  2011     RMadrid    32      4       2
5  2012     RMadrid    26      7       5
6  2010  ValenciaCF    21      8       9
7  2011  ValenciaCF    17     10      11
8  2012  ValenciaCF    19      8      11

### Adding Columns to Pandas DataFrames

Awarding 3 points for each win
Awarding 1 points for each draw
Awarding 0 points for each loss

In [34]:
# notice that RHS is the pandas series
football["points"] = 3*football["wins"] + 1*football["draws"] + 0*football["losses"]  # runs through this for each row
football.head()

year         team  wins  draws  losses  points
0  2010  FCBarcelona    30      6       2      96
1  2011  FCBarcelona    28      7       3      91
2  2012  FCBarcelona    32      4       2     100
3  2010      RMadrid    29      5       4      92
4  2011      RMadrid    32      4       2     100

There are several takeaways from this exercise. First, if we want to create a new column in our DataFrame, we simply have to assign the DataFrame indexed by the new column name to some valid Panda Series . The second takeaway is that we can scale and add Pandas series in the same way Numpy Arrays

## Sorting in Pandas

Now suppose we want to rank the team-season combinations form the greates to the least number of points. One way we could do this would be to sort he DataFrame by the __points__ column. We can do it as follows

In [35]:
# essentially the same as SQL
football_sorted = football.sort_values(by="points", ascending=False)  # RETURNS A NEW DATAFRAME
football_sorted.head()

# if you want to sort the data of the same object then you could add a third parameter: inplace=True

year         team  wins  draws  losses  points
2  2012  FCBarcelona    32      4       2     100
4  2011      RMadrid    32      4       2     100
0  2010  FCBarcelona    30      6       2      96
3  2010      RMadrid    29      5       4      92
1  2011  FCBarcelona    28      7       3      91

### Slicing and Dicing Pandas DataFrames

```loc``` slices rows and columns by their __names__

```iloc``` slices rows and columns by their __integer index order__, much like slicing in Numpy

In [41]:
football_sorted.iloc[:9]    # essentially just accessing a sub-array, not inclusive

year         team  wins  draws  losses  points
2  2012  FCBarcelona    32      4       2     100
4  2011      RMadrid    32      4       2     100
0  2010  FCBarcelona    30      6       2      96
3  2010      RMadrid    29      5       4      92
1  2011  FCBarcelona    28      7       3      91
5  2012      RMadrid    26      7       5      85
6  2010   ValenciaCF    21      8       9      71
8  2012   ValenciaCF    19      8      11      65
7  2011   ValenciaCF    17     10      11      61

In [42]:
football_sorted.loc[:4]

year         team  wins  draws  losses  points
2  2012  FCBarcelona    32      4       2     100
4  2011      RMadrid    32      4       2     100

```loc``` gives you the slice of all sorted datafram elements until it found a row named __4__. That just happens to be the name, remember that it could be anything. 

```iloc``` pretty much just give me the elements from that slice from the DataFrame

Now suppose we want the first four rows of the DataFrame, but only the first three colums. Since we're slicing by integer order, we'll use  𝚒𝚕𝚘𝚌 

In [43]:
football_sorted.iloc[:4,:3]

year         team  wins
2  2012  FCBarcelona    32
4  2011      RMadrid    32
0  2010  FCBarcelona    30
3  2010      RMadrid    29

Now, suppose that we want to mix slicing by numerical order and slicing by name.  This can get kinda tricky. For instance, suppose we wanted the first four rows of the DataFrame, and just the columns corresponding to **team** and **points**.  So we're really doing two slices: one by integer index order, and one by name.  One **INADVISABLE** way to do this is to chain multiple calls to $\texttt{iloc}$ and $\texttt{loc}$ together. 

__What we are going to end up doing here is chain operations__

In [46]:
football_sorted.iloc[:4].loc[:,["team", "points"]]

team  points
2  FCBarcelona     100
4      RMadrid     100
0  FCBarcelona      96
3      RMadrid      92

In [48]:
# better way to do what we just did above

x = football_sorted.index[:4]   # returns you the list of indexes from up to that given indice 
football_sorted.loc[x,["team","points"]]


# doing this is a lot cleaner 


team  points
2  FCBarcelona     100
4      RMadrid     100
0  FCBarcelona      96
3      RMadrid      92